name: Update GitHub Heatmap Dark Theme

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch dark theme heatmap
        run: |
          curl -s "https://github.com/users/Anamika770/contributions" \
          | sed 's/<svg /<svg style="background-color:#0d1117;" /' \
          | sed 's/fill="#767676"/fill="#ffffff"/g' \
          | sed 's/fill="#000000"/fill="#ffffff"/g' \
          > heatmap.svg

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add heatmap.svg
          git commit -m "Update dark theme heatmap" || echo "No changes"
          git push
