name: Update GitHub Contribution Heatmap

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Download GitHub heatmap
        run: |
          python - <<'EOF'
          import requests
          from bs4 import BeautifulSoup

          username = "Anamika770"
          url = f"https://github.com/users/{username}/contributions"
          r = requests.get(url)
          soup = BeautifulSoup(r.text, "html.parser")

          svg = soup.find("svg")
          with open("heatmap.svg", "w", encoding="utf-8") as f:
              f.write(str(svg))
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add heatmap.svg
          git commit -m "Update GitHub contribution heatmap"
          git push
