name: Update GitHub Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download latest contribution graph
        run: |
          curl "https://github-readme-activity-graph.vercel.app/graph?username=Anamika770&bg_color=0d1117&color=ffffff&line=40c463&point=40c463&area=true&hide_border=true" -o contributions.svg

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add contributions.svg
          git commit -m "Update GitHub contribution graph"
          gi
